name: CD

on:
  push:
    branches: [ main ]

jobs:     
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2      

    - name: Run Script
      run: pm2 restart main.py --interpreter python3 -- $token
      env:
        token: ${{ secrets.DISCORD_TOKEN }}
