name: CD

on:
  push:
    branches: [ main ]

jobs:     
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: cd github/WPU-Bot-2.0 && git pull origin main && pm2 restart main.py --interpreter python3 -- ${{ secrets.DISCORD_TOKEN }}
