name: CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install flake8 pytest 
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the action if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  deploy:
    needs: test
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
   - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install flake8 pytest 
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run script
      run: | 
        python3 main.py $token
      env:
        token: ${{ secrets.DISCORD_TOKEN }}
    